<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>MBMC Host</title>
<link href="/mchp.css" rel="stylesheet" type="text/css" />
<script src="/mchp.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 5px 5px"><img src="/mbmc.gif" alt="MBMC" /></div>

<div id="title"><div class="right">MBMC Host</div><span id="hello">&nbsp;</span></div>

<div id="menu">
<a href="/index.htm">Status Display</a>
<a href="/dynvars.htm">Status Plots</a>
<a href="/dynvars_e.htm">Harvest Plots</a>
<a href="/forms.htm">Controller Commands</a>
<a href="/dynvars_a.htm">Power Cube</a>
<a href="/upload.htm">File Uploads</a>
<a href="/email">Send E-mail</a>
<a href="/dyndns">Dynamic DNS</a>
<a href="/protect/config.htm">Network Configuration</a>
<a href="/snmp/snmpconfig.htm">SNMP Configuration</a>
</div>